name: CI/CD Pipeline

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r ci-cd-app/requirements.txt

      - name: Run HTTP Test
        run: |
          python ci-cd-app/app.py &
          sleep 3
          curl -f http://localhost:5000 || exit 1

  deploy:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and Deploy with Docker Compose
        run: |
          docker compose -f ci-cd-app/docker-compose.yml up -d --build
          sleep 3
          curl -f http://localhost:8080 || exit 1
